[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

# Dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@layerzero-labs/solidity-examples/=lib/solidity-examples/",
    "@layerzero-v2/oapp/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/contracts/oapp/",
    "@layerzero-v2/protocol/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/contracts/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzerolabs/lz-evm-oapp-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "forge-std/=lib/forge-std/src/",
]
